name = "Peer Trenches"
prefix = "Peer_Trenches"
author = "[W] Peer"
sig_version = 3
version = "0.6.3"
reuse_private_key = false
    files = [
        "mod.cpp",
        "*.paa",
        "LICENSE",
        "readme.txt"
    ]
include = ["./include"]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip @Peer_Trenches"
]
