#define MAINPREFIX x
#define PREFIX Peer_Trenches
#define DEBUG_MODE_FULL
#include "script_version.hpp"

#define VERSION MAJOR.MINOR.PATCHLVL-BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 2.02
#define REQUIRED_CBA_VERSION { 3, 5, 0 }
#define REQUIRED_ACE_VERSION { 3, 11, 0 }

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(PREFIX COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(PREFIX COMPONENT)
#endif
